# Generated by Django 4.0.4 on 2022-05-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(blank=True, help_text='Entry title', max_length=100),
        ),
    ]
