# Generated by Django 4.0.4 on 2022-06-08 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='entry_brief',
        ),
    ]
