# Generated by Django 4.0.4 on 2022-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_remove_entry_entry_brief'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='time_edited',
        ),
        migrations.AddField(
            model_name='entry',
            name='edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
