# Generated by Django 4.0.4 on 2022-06-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry_entry_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default='Programming', max_length=60),
        ),
    ]
