# Generated by Django 4.0.4 on 2022-06-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_remove_entry_time_edited_entry_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='time_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
