# Generated by Django 4.0.4 on 2022-06-01 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_alter_entry_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_topic',
            field=models.ForeignKey(default='Programming', on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
        ),
    ]
