# Generated by Django 4.0.4 on 2022-06-02 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_alter_entry_entry_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.TextField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=60),
        ),
    ]
