# Generated by Django 4.0.4 on 2022-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0005_topic_topic_description_alter_entry_entry_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_owner',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
