# Generated by Django 4.0.4 on 2022-06-07 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_alter_topic_topic_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_owner',
            new_name='host',
        ),
    ]
