# Generated by Django 4.0.4 on 2022-06-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_alter_topic_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='host',
            new_name='owner',
        ),
    ]
